In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os 
import glob
from skimage.feature import hog
import time
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import pickle
#sklearn


In [2]:
"""
데이터 적재 
"""

'\n데이터 적재 \n'

In [3]:
car_images = []
noncar_images = []
print('0')
for root, dirs, files in os.walk('./data/vehicles/'):
    print("1")
    print("root"+ root)
    print( dirs)
    print("="*30)
    print( files)
    print("-"*30)
    for file in files:
        print("2")
        if file.endswith(".png"):
            print('3')
            car_images.append(os.path.join(root, file))
            print('4')
            
print('no0')
for root, dirs, files in os.walk('./data/non-vehicles/'):
    print("no1")
    print("no_root"+ root)
    print( dirs)
    print("#"*30)
    print( files)
    print("*"*30)
    for file in files:
        print("no2")
        if file.endswith(".png"):
            print('no3')
            noncar_images.append(os.path.join(root, file))
            print('no4')

0
1
root./data/vehicles/
['GTI_Far', 'GTI_Left', 'GTI_MiddleClose', 'GTI_Right', 'KITTI_extracted']
[]
------------------------------
1
root./data/vehicles/GTI_Far
[]
['image0000.png', 'image0001.png', 'image0002.png', 'image0003.png', 'image0004.png', 'image0005.png', 'image0006.png', 'image0007.png', 'image0008.png', 'image0009.png', 'image0010.png', 'image0014.png', 'image0015.png', 'image0016.png', 'image0018.png', 'image0019.png', 'image0021.png', 'image0022.png', 'image0023.png', 'image0024.png', 'image0027.png', 'image0029.png', 'image0030.png', 'image0033.png', 'image0036.png', 'image0037.png', 'image0039.png', 'image0040.png', 'image0041.png', 'image0042.png', 'image0043.png', 'image0044.png', 'image0045.png', 'image0046.png', 'image0047.png', 'image0048.png', 'image0049.png', 'image0050.png', 'image0051.png', 'image0052.png', 'image0053.png', 'image0054.png', 'image0064.png', 'image0065.png', 'image0066.png', 'image0067.png', 'image0068.png', 'image0069.png', 'image0070.png',

3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4


4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2


2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3


3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4


4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2
3
4
2


no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2


no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2


no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2


no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2


no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2


no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4
no2
no3
no4


In [4]:
car_images

['./data/vehicles/GTI_Far\\image0000.png',
 './data/vehicles/GTI_Far\\image0001.png',
 './data/vehicles/GTI_Far\\image0002.png',
 './data/vehicles/GTI_Far\\image0003.png',
 './data/vehicles/GTI_Far\\image0004.png',
 './data/vehicles/GTI_Far\\image0005.png',
 './data/vehicles/GTI_Far\\image0006.png',
 './data/vehicles/GTI_Far\\image0007.png',
 './data/vehicles/GTI_Far\\image0008.png',
 './data/vehicles/GTI_Far\\image0009.png',
 './data/vehicles/GTI_Far\\image0010.png',
 './data/vehicles/GTI_Far\\image0014.png',
 './data/vehicles/GTI_Far\\image0015.png',
 './data/vehicles/GTI_Far\\image0016.png',
 './data/vehicles/GTI_Far\\image0018.png',
 './data/vehicles/GTI_Far\\image0019.png',
 './data/vehicles/GTI_Far\\image0021.png',
 './data/vehicles/GTI_Far\\image0022.png',
 './data/vehicles/GTI_Far\\image0023.png',
 './data/vehicles/GTI_Far\\image0024.png',
 './data/vehicles/GTI_Far\\image0027.png',
 './data/vehicles/GTI_Far\\image0029.png',
 './data/vehicles/GTI_Far\\image0030.png',
 './data/ve

In [5]:
noncar_images

['./data/non-vehicles/Extras\\extra1.png',
 './data/non-vehicles/Extras\\extra10.png',
 './data/non-vehicles/Extras\\extra100.png',
 './data/non-vehicles/Extras\\extra1000.png',
 './data/non-vehicles/Extras\\extra1001.png',
 './data/non-vehicles/Extras\\extra1002.png',
 './data/non-vehicles/Extras\\extra1003.png',
 './data/non-vehicles/Extras\\extra1004.png',
 './data/non-vehicles/Extras\\extra1005.png',
 './data/non-vehicles/Extras\\extra1006.png',
 './data/non-vehicles/Extras\\extra1007.png',
 './data/non-vehicles/Extras\\extra1008.png',
 './data/non-vehicles/Extras\\extra1009.png',
 './data/non-vehicles/Extras\\extra101.png',
 './data/non-vehicles/Extras\\extra1010.png',
 './data/non-vehicles/Extras\\extra1011.png',
 './data/non-vehicles/Extras\\extra1012.png',
 './data/non-vehicles/Extras\\extra1013.png',
 './data/non-vehicles/Extras\\extra1014.png',
 './data/non-vehicles/Extras\\extra1015.png',
 './data/non-vehicles/Extras\\extra102.png',
 './data/non-vehicles/Extras\\extra103.png

In [6]:
#테스트용 100개 이미지
car_images = car_images[:100]
noncar_images = noncar_images[:100]
imgs = car_images + noncar_images

In [7]:
#파라미터들 의 값
#svc 머신러닝 - 이미 선언됨
#X_scaler - 머신러닝 부분인데 물어보기
#HOG 알고리즘 파라미터
orient = 9
pix_per_cell = (4, 4)
cell_per_block = (2, 2)
#이미지 리사이즈 파라미터
spatial = (32, 32)
#히스토그램 파라미터
hist_bins = [32]

In [8]:
"""
이미지 리사이즈
"""
def img_resize(img, spatial):
    src = cv2.imread(img)
    src_resize = cv2.resize(src, spatial) # fx: 가로 사이즈의 배수
    resize_feature = src_resize.flatten()

    return resize_feature

In [9]:
"""
hog 알고리즘 
"""
def hog_img(img, orient, pix_per_cell, cell_per_block):
    hog_img = mpimg.imread(img)
    gray_img = cv2.cvtColor(hog_img, cv2.COLOR_BGR2GRAY)
    
    hog_feature, hog_image = hog(gray_img, orientations=orient, pixels_per_cell=pix_per_cell, 
                                     cells_per_block=cell_per_block, block_norm='L2-Hys', 
                                     transform_sqrt=False, visualize = True, 
                                     feature_vector=False)
    
    hog_feature = hog_feature.flatten()
        
    return hog_feature

In [10]:
"""
히스토그램 분석
"""
def hist_img(img, hist_bins ):
    
    src = cv2.imread(img)
    hist1_b = cv2.calcHist(images = [src], 
                         channels = [0], 
                         mask = None, 
                         histSize = hist_bins, 
                         ranges = [0, 255])

    hist2_g = cv2.calcHist(images = [src], 
                         channels = [1], 
                         mask = None, 
                         histSize = hist_bins, 
                         ranges = [0, 255])

    hist3_r = cv2.calcHist(images = [src], 
                         channels = [2], 
                         mask = None, 
                         histSize = hist_bins, 
                         ranges = [0, 255])

    hist1_b_f = hist1_b.flatten()
    hist2_g_f = hist2_g.flatten()
    hist3_r_f = hist3_r.flatten()

    hist_feature = np.concatenate([hist1_b_f, hist2_g_f, hist3_r_f]) # 특성 합치는 함수

    return hist_feature

In [11]:
"""
레이블 - 머신러닝 정답 
"""
label_list = []
for i in range(len(car_images)):
    answer=1
    label_list.append(answer)

    
for i in range(len(noncar_images)):
    notanswer=0
    label_list.append(notanswer)

In [12]:
labeled = np.array(label_list)

In [14]:
feature_list = []
for file in imgs:
    feature1 = img_resize(file, spatial )
    feature2 = hog_img(file, orient, pix_per_cell, cell_per_block,)
    feature3 = hist_img(file, hist_bins )
    feature = np.concatenate((feature1, feature2, feature3))
    feature_list.append(feature)
X = np.array(feature_list)

In [15]:
X.shape

(200, 11268)

In [16]:
X.dtype

dtype('float64')

In [17]:
X

array([[163., 168., 156., ...,   0.,   0.,   0.],
       [163., 168., 156., ...,   0.,   0.,   0.],
       [139., 152., 143., ...,   0.,   0.,   0.],
       ...,
       [108., 108., 114., ...,   0.,   0.,   0.],
       [ 89.,  86.,  92., ...,   2.,   2.,   0.],
       [ 51.,  39.,  44., ...,   0.,   0.,   0.]])

In [18]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

In [19]:
X_scaled = std_scaler.fit_transform(X)

In [20]:
y= labeled

In [21]:
y.shape

(200,)

In [22]:
"""
머신러닝 부분 - 
문제는 값이 -1~1 을 넘어선값
"""

'\n머신러닝 부분 - \n문제는 값이 -1~1 을 넘어선값\n'

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y)

### 모델링

In [25]:
from sklearn.svm import LinearSVC

In [26]:
lin_SVC = LinearSVC()

In [27]:
lin_SVC.fit(X_train, y_train)

LinearSVC()

In [28]:
from sklearn.svm import SVC

In [29]:
svc = SVC()

In [30]:
svc.fit(X_train, y_train)

SVC()

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
r_forest = RandomForestClassifier()

In [33]:
r_forest.fit(X_train, y_train)

RandomForestClassifier()

### 모델 평가

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
y_scores_lin_SVC = cross_val_score(lin_SVC, X_train, y_train, scoring="accuracy", cv=5, n_jobs=-1)

In [36]:
y_scores_lin_SVC

array([1., 1., 1., 1., 1.])

In [37]:
y_scores_lin_SVC.mean()

1.0

In [38]:
y_scores_SVC = cross_val_score(svc, X_train, y_train, scoring="accuracy", cv=5, n_jobs=-1)

In [39]:
y_scores_SVC

array([1.        , 1.        , 1.        , 1.        , 0.93333333])

In [40]:
y_scores_SVC.mean()

0.9866666666666667

In [41]:
y_scores_r_forest = cross_val_score(r_forest, X_train, y_train, scoring="accuracy", cv=5, n_jobs=-1)

In [42]:
y_scores_r_forest

array([1.        , 1.        , 0.93333333, 1.        , 0.83333333])

In [43]:
y_scores_r_forest.mean()

0.9533333333333334

### 예측

In [44]:
final_model = svc

In [45]:
y_pred = final_model.predict(X_test)

In [46]:
y_pred

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1])

In [47]:
"""
Data Saving to Pickle - Car Detector랑 연결함
"""

'\nData Saving to Pickle - Car Detector랑 연결함\n'

In [48]:
dist_pickle = {}
dist_pickle['svc'] = svc
dist_pickle['scaler'] = std_scaler
dist_pickle['orient'] = orient
dist_pickle['pix_per_cell'] = pix_per_cell
dist_pickle['cell_per_block'] = cell_per_block
dist_pickle['spatial'] = spatial
dist_pickle['hist_bins'] = hist_bins
pickle.dump(dist_pickle, open('svc_pickle.p', 'wb'))

print('Classifier parameters saved to file!')

"""
 코드 특성들의 파라미터를 저장해둠
 dist_pickle['svc'] = svc - 예측모델
dist_pickle['scaler'] = X_scaler
dist_pickle['orient'] = orient
dist_pickle['pix_per_cell'] = pix_per_cell
dist_pickle['cell_per_block'] = cell_per_block
dist_pickle['spatial'] = spatial
dist_pickle['hist_bins'] = hist_bins
"""

Classifier parameters saved to file!


"\n 코드 특성들의 파라미터를 저장해둠\n dist_pickle['svc'] = svc - 예측모델\ndist_pickle['scaler'] = X_scaler\ndist_pickle['orient'] = orient\ndist_pickle['pix_per_cell'] = pix_per_cell\ndist_pickle['cell_per_block'] = cell_per_block\ndist_pickle['spatial'] = spatial\ndist_pickle['hist_bins'] = hist_bins\n"